### ISSUE TITLE
getDatesOfNextWeeks should be able to show weekends

### ISSUE THREAD

**Issue by junelau** [jitbug/helpers#3]
Currently, it will only show Mon-Fri, even if there are events on Sat or Sun.
https://github.com/jitbug/helpers/blob/64b0c63d23ea56bc42300f5406520e61c3ffb893/src/dates/index.ts#L116

In Jitbug, a modified version has been created:
https://github.com/jitbug/jitbug/blob/faa244c433a04739ecb222a6e1b343461c8ffb58/pwa/src/components/page-candidate-schedules/page-candidate-schedules.tsx#L98-L109

**Comment by simonhaenisch** [comment]
This helper doesn't have a concept of events, it's a lot more generic (just gives you an array of moments for the working days of the next n weeks).

It could benefit from an `includeWeekends` param though.
